### ISSUE TITLE
Game not starting

### ISSUE THREAD

**Issue by FlyFunMan** [AddstarMC/Minigames#213]
**Note: for support questions, please use SpigotMC.org**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
This is a bug report.

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
When a game starts, nobody is teleported. They also don't get any of the set permissions. It is as if the game has not started at all. When I use the command /mg start <minigame>, it says the game is started.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem, screenshots ok**
The only way to reproduce the problem is simply starting a minigame, any game mode.

* **What is the expected behavior?**
The expected behavior is that the game starts.

* **What is the motivation/use case for changing the behavior?**
This bug prevents the minigames from working properly, so I really want to know how I would fix this. I don't know why it started happening, it was working fine one day and the next it stopped. no changes were made to the server.

* **Please tell us about your environment:**
- Spigot Version: git-Spigot-2474d93-e693496 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
- Minigames version: 1.12.1- build #299

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, gitter, etc)

**Comment by Narimm** [comment]
Can you confirm the Minigames Version please.

**Comment by FlyFunMan** [comment]
![Minecraft 1 13 2 3_21_2019 3_57_40 PM](https://user-images.githubusercontent.com/45148010/54781250-249dc900-4bf2-11e9-8905-2544a43f0c6e.png)

**Comment by Castiella** [comment]
Also having this issue. Following.

**Comment by Kamg300** [comment]
I'm having the same issue with version #299, on 1.13.2.

**Comment by OutlawedBit** [comment]
Also having the same issue with the game not starting with the #299 snapshot on Spigot 1.13.2.

**Comment by iA3Gamer** [comment]
First you have to choose "game mechanic" and then "type" and the lobby will get fine

**Comment by Schpammer** [comment]
Yep. Same with #299 on 1.13.2.

**Comment by Rytiggy** [comment]
Same with me. but only for multiplayer game modes. Any idea what's going on?

**Comment by iA3Gamer** [comment]
> Same with me. but only for multiplayer game modes. Any idea what's going on?

You selected game mechanic and type options?

**Comment by Rytiggy** [comment]
@iA3Gamer they should be.  Ive added both of the games that dont work. any single player games still work. Its like the plugin isnt putting the players on teams
# Game Config
```
PirateBay:
  playerWaitTime: 10
  loadouts:
    default:
      items:
        '0':
          ==: org.bukkit.inventory.ItemStack
          v: 1631
          type: LEATHER_CHESTPLATE
          meta:
            ==: ItemMeta
            meta-type: LEATHER_ARMOR
            color:
              ==: Color
              RED: 254
              BLUE: 61
              GREEN: 216
        '1':
          ==: org.bukkit.inventory.ItemStack
          v: 1631
          type: LEATHER_LEGGINGS
        '2':
          ==: org.bukkit.inventory.ItemStack
          v: 1631
          type: BOW
        '3':
          ==: org.bukkit.inventory.ItemStack
          v: 1631
          type: ARROW
          amount: 64
        '9':
          ==: org.bukkit.inventory.ItemStack
          v: 1631
          type: LEATHER_BOOTS
        '10':
          ==: org.bukkit.inventory.ItemStack
          v: 1631
          type: LEATHER_HELMET
      team: YELLOW
    Blue:
      items:
        '0':
          ==: org.bukkit.inventory.ItemStack
          v: 1631
          type: LEATHER_CHESTPLATE
          meta:
            ==: ItemMeta
            meta-type: LEATHER_ARMOR
            color:
              ==: Color
              RED: 60
              BLUE: 170
              GREEN: 68
        '1':
          ==: org.bukkit.inventory.ItemStack
          v: 1631
          type: LEATHER_LEGGINGS
        '2':
          ==: org.bukkit.inventory.ItemStack
          v: 1631
          type: LEATHER_HELMET
        '3':
          ==: org.bukkit.inventory.ItemStack
          v: 1631
          type: LEATHER_BOOTS
        '4':
          ==: org.bukkit.inventory.ItemStack
          v: 1631
          type: ARROW
          amount: 64
        '5':
          ==: org.bukkit.inventory.ItemStack
          v: 1631
          type: BOW
      team: BLUE
  teams:
    BLUE:
      displayName: Blue Team
      startpos:
        '0':
          x: 1851.4164451798126
          y: 75.0
          z: 952.7534013153893
          world: worlds/mapWoods
          yaw: 145.55534
          pitch: 3.8342953
        '1':
          x: 1851.4164451798126
          y: 75.0
          z: 952.7534013153893
          world: worlds/mapWoods
          yaw: 145.55534
          pitch: 3.8342953
        '2':
          x: 1851.4164451798126
          y: 75.0
          z: 952.7534013153893
          world: worlds/mapWoods
          yaw: 145.55534
          pitch: 3.8342953
      maxPlayers: 5
    YELLOW:
      displayName: Yellow Team
      startpos:
        '0':
          x: 1811.5751224421076
          y: 75.0
          z: 900.6724480600102
          world: worlds/mapWoods
          yaw: 320.94357
          pitch: 5.9553432
        '1':
          x: 1811.5751224421076
          y: 75.0
          z: 900.6724480600102
          world: worlds/mapWoods
          yaw: 320.94357
          pitch: 5.9553432
        '2':
          x: 1811.5751224421076
          y: 75.0
          z: 900.6724480600102
          world: worlds/mapWoods
          yaw: 320.94357
          pitch: 5.9553432
        '3':
          x: 1811.5751224421076
          y: 75.0
          z: 900.6724480600102
          world: worlds/mapWoods
          yaw: 320.94357
          pitch: 5.9553432
        '4':
          x: 1811.5751224421076
          y: 75.0
          z: 900.6724480600102
          world: worlds/mapWoods
          yaw: 320.94357
          pitch: 5.9553432
      maxPlayers: 5
  reward-scheme: standard
  rewards: {}
  reward:
    '0':
      type: ITEM
      rarity: NORMAL
      data:
        ==: org.bukkit.inventory.ItemStack
        v: 1631
        type: DIAMOND
  reward2:
    '0':
      type: ITEM
      rarity: NORMAL
      data:
        ==: org.bukkit.inventory.ItemStack
        v: 1631
        type: DIAMOND
  type: MULTIPLAYER
  endpos:
    x: 1477.7167034380573
    y: 70.5
    z: 511.69557319109884
    world: worlds/mapWoods
    yaw: -180.10422
    pitch: -0.8461476
  regenarea:
    '1':
      x: 1793.0
      y: 4.0
      z: 858.0
      world: worlds/mapWoods
      yaw: 0.0
      pitch: 0.0
    '2':
      x: 1886.0
      y: 125.0
      z: 992.0
      world: worlds/mapWoods
      yaw: 0.0
      pitch: 0.0
  lobbypos:
    x: 1832.4507240780547
    y: 129.0
    z: 924.4843491093151
    world: worlds/mapWoods
    yaw: 88.02131
    pitch: 89.56325
  degenrandom: 1
  lives: 3.0
  scoretype: kills
  flags: []
  enabled: true
  startpos:
    '0':
      x: 1818.2158117660263
      y: 88.33985541241684
      z: 924.6846665059848
      world: worlds/mapWoods
      yaw: 256.12012
      pitch: 30.040142
    '1':
      x: 1812.5527106165011
      y: 75.0
      z: 900.0849626440894
      world: worlds/mapWoods
      yaw: 311.3944
      pitch: -2.218659
    '2':
      x: 1851.2639533586096
      y: 75.0
      z: 952.1357543168897
      world: worlds/mapWoods
      yaw: 132.88383
      pitch: -0.8462334
  timer: 1
  startWaitTime: 3
  quitpos:
    x: 1477.7167034380573
    y: 70.5
    z: 511.69557319109884
    world: worlds/mapWoods
    yaw: -180.2914
    pitch: -0.15981203
  scoreboards: {}
```
# Game config
```
Infection:
  loadouts:
    Red:
      items:
        '0':
          ==: org.bukkit.inventory.ItemStack
          v: 1631
          type: DIAMOND_SWORD
        '1':
          ==: org.bukkit.inventory.ItemStack
          v: 1631
          type: LEATHER_CHESTPLATE
        '2':
          ==: org.bukkit.inventory.ItemStack
          v: 1631
          type: ARROW
          amount: 12
      team: RED
    default: {}
    Blue:
      items:
        '0':
          ==: org.bukkit.inventory.ItemStack
          v: 1631
          type: LEATHER_CHESTPLATE
        '1':
          ==: org.bukkit.inventory.ItemStack
          v: 1631
          type: BOW
        '2':
          ==: org.bukkit.inventory.ItemStack
          v: 1631
          type: ARROW
          amount: 6
      team: BLUE
  teams:
    BLUE:
      displayName: Blue Team
      maxPlayers: 5
    RED:
      displayName: Red Team
      maxPlayers: 10
  defaultwinner: BLUE
  reward-scheme: standard
  rewards: {}
  type: MULTIPLAYER
  lobbypos:
    x: 152.2119935606412
    y: 40.0
    z: 879.9260168454744
    world: worlds/Minigame
    yaw: -0.94919825
    pitch: -3.6812053
  scoretype: infection
  flags: []
  enabled: true
  startpos:
    '0':
      x: 193.28048835263039
      y: 52.0
      z: 852.7319545332706
      world: worlds/Minigame
      yaw: -184.05688
      pitch: 3.9938345
    '1':
      x: 166.5553572214791
      y: 52.0
      z: 861.7394101583019
      world: worlds/Minigame
      yaw: -92.723854
      pitch: -3.493749
    '2':
      x: 190.59624817421215
      y: 47.0
      z: 870.6482767088917
      world: worlds/Minigame
      yaw: -150.37648
      pitch: -9.48364
    '3':
      x: 229.33136825029237
      y: 50.0
      z: 895.2261440402874
      world: worlds/Minigame
      yaw: -257.33673
      pitch: -4.679404
    '4':
      x: 328.39914682334785
      y: 72.0
      z: 1349.318789294775
      world: worlds/Minigame
      yaw: -90.91058
      pitch: -12.853059
    '5':
      x: 152.42135600423975
      y: 40.0
      z: 879.9132948893792
      world: worlds/Minigame
      yaw: 2.7944503
      pitch: -6.0521827
    '6':
      x: 153.41667682003927
      y: 52.0
      z: 861.614056824715
      world: worlds/Minigame
      yaw: -92.730804
      pitch: -9.920719
    '7':
      x: 167.5695079043762
      y: 76.0
      z: 831.5906721040919
      world: worlds/Minigame
      yaw: -74.44952
      pitch: 2.9948816
  timer: 600
  quitpos:
    x: 328.39914682334785
    y: 72.0
    z: 1349.318789294775
    world: worlds/Minigame
    yaw: -90.97298
    pitch: -13.040241
  scoreboards: {}
```


# Global Config
```
# 
# Whether the plugin should check for updates

saveInventory: true
requireEmptyInventory: false
forceload: false
debug: false
broadcastCompletion: true
playSounds: true
regeneration:
  maxDelay: 10
updateChecker: false
lang: en_AU
tool: BLAZE_ROD
warnings: true
outputCMDToFile: false
backend:
  type: sqlite
  host: localhost:3306
  database: database
  username: username
  password: password
  properties:
    useSSL: false
multiplayer:
  waitforplayers: 10
  startcountdown: 5
  timerMessageInterval:
  - 900
  - 600
  - 300
  - 60
  - 30
  - 10
  - 5
  - 4
  - 3
  - 2
  - 1
  ctf:
    flagrespawntime: 60
  floordegenerator:
    time: 30
treasurehunt:
  waittime: 3600
minigames:
- PirateBay
- Infection
- LastManStanding
disabledCommands:
- home
- warp
- spawn
```
